### ISSUE TITLE
Credenciales en repositorio

### ISSUE THREAD

**Issue by sanflores** [Varesi-code/CTD#1]
https://github.com/Varesi-code/CTD/blob/6c905f5ea1f87e3ef76fb796941bab34f640b242/B3/2-Infra/bucket/credenciales%20aws.txt

Por cuestiones de seguridad y como mejores prácticas nunca se deben subir credenciales de ningún tipo a un repositorio.

**Comment by Varesi-code** [comment]
Perdon! error sin mala intecion. Borrado
